// <auto-generated />
using System;
using BootcampMarket.Data.MSSQL.Context.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BootcampMarket.Data.MSSQL.Migrations.EntityFramework.Migrations
{
    [DbContext(typeof(BootcampMarketDbContext))]
    [Migration("20211030160324_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength(true);

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.CustomerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DistrictId");

                    b.ToTable("CustomerAddress");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.CustomerDetail", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerId")
                        .HasName("PK_CustomerDetail_1");

                    b.ToTable("CustomerDetail");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("District");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Discount")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.ProductComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductComment");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength(true);

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.City", b =>
                {
                    b.HasOne("BootcampMarket.Data.MSSQL.Entity.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK_City_Country")
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.CustomerAddress", b =>
                {
                    b.HasOne("BootcampMarket.Data.MSSQL.Entity.City", "City")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_CustomerAddress_City")
                        .IsRequired();

                    b.HasOne("BootcampMarket.Data.MSSQL.Entity.Country", "Country")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK_CustomerAddress_Country")
                        .IsRequired();

                    b.HasOne("BootcampMarket.Data.MSSQL.Entity.Customer", "Customer")
                        .WithMany("CustomerAddressCustomers")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_CustomerAddress_Customer")
                        .IsRequired();

                    b.HasOne("BootcampMarket.Data.MSSQL.Entity.District", "District")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("FK_CustomerAddress_District")
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Customer");

                    b.Navigation("District");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.CustomerDetail", b =>
                {
                    b.HasOne("BootcampMarket.Data.MSSQL.Entity.Customer", "Customer")
                        .WithOne("CustomerDetail")
                        .HasForeignKey("BootcampMarket.Data.MSSQL.Entity.CustomerDetail", "CustomerId")
                        .HasConstraintName("FK_CustomerDetail_Customer1")
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.District", b =>
                {
                    b.HasOne("BootcampMarket.Data.MSSQL.Entity.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_District_City")
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.ProductComment", b =>
                {
                    b.HasOne("BootcampMarket.Data.MSSQL.Entity.Customer", "Customer")
                        .WithMany("ProductCommentCustomers")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_ProductComment_Customer")
                        .IsRequired();

                    b.HasOne("BootcampMarket.Data.MSSQL.Entity.Product", "Product")
                        .WithMany("ProductComments")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_ProductComment_Product")
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.City", b =>
                {
                    b.Navigation("CustomerAddresses");

                    b.Navigation("Districts");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("CustomerAddresses");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.Customer", b =>
                {
                    b.Navigation("CustomerAddressCustomers");

                    b.Navigation("CustomerDetail");

                    b.Navigation("ProductCommentCustomers");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.District", b =>
                {
                    b.Navigation("CustomerAddresses");
                });

            modelBuilder.Entity("BootcampMarket.Data.MSSQL.Entity.Product", b =>
                {
                    b.Navigation("ProductComments");
                });
#pragma warning restore 612, 618
        }
    }
}
